application: sample 
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: favicon.ico 
  upload: favicon.ico 
  expiration: "3s"

- url: /static/(.*js)
  static_files: static/js/\1
  upload: static/js/(.*)
  expiration: "3s"

- url: /static/(.*\.(css|less))
  static_files: static/css/\1
  upload: static/css/(.*)
  expiration: "3s"

- url: /static/(.*\.(png|jpg|gif))
  static_files: static/img/\1
  upload: static/css/(.*)
  expiration: "3s"

# /books/static/test.js -> apps/books/views/static/js/test.js
- url: /(.*)/static/(.*js)
  static_files: apps/\1/views/static/js/\2
  upload: apps/(.*)/views/static/js/(.*)
  expiration: "3s"

# /books/static/test.css -> apps/books/views/static/css/test.css
- url: /(.*)/static/(.*\.(css|less))
  static_files: apps/\1/views/static/css/\2
  upload: apps/(.*)/views/static/js/(.*)
  expiration: "3s"

# /books/static/test.png -> apps/books/views/static/img/test.png
- url: /(.*)/static/(.*\.(gif|png|jpg))
  static_files: apps/\1/views/static/img/\2
  upload: apps/(.*)/views/static/img/(.*)
  expiration: "3s"

# /books/static/test.json -> apps/books/views/static/test.json
- url: /(.*)/static/(.*)
  static_files: apps/\1/views/static/\2
  upload: apps/(.*)/views/static/(.*)
  expiration: "3s"

# Private task queue requests.
- url: /task/.*
  script: gae.py
  login: admin

# All dynamic content.
- url: .*
  script: gae.py

builtins:
- datastore_admin: on
- admin_redirect: on
- appstats: on

